export const __TEST_RUNNER = '__TEST_RUNNER';

export const ADD_ITEM_TO_WORKSPACE = 'ADD_ITEM_TO_WORKSPACE';
export const REMOVE_ITEM_FROM_WORKSPACE = 'REMOVE_ITEM_FROM_WORKSPACE';
export const UPDATE_QUERY_STRING = 'UPDATE_QUERY_STRING';
export const UPDATE_QUERY_OBJECT = 'UPDATE_QUERY_OBJECT';
export const CLEAR_WORKSPACE = 'CLEAR_WORKSPACE';
