export const __TEST_RUNNER = '__TEST_RUNNER';
export const RESET = 'RESET';

export const ADD_ITEM_TO_WORKSPACE = 'ADD_ITEM_TO_WORKSPACE';
export const REMOVE_ITEM_FROM_WORKSPACE = 'REMOVE_ITEM_FROM_WORKSPACE';
export const UPDATE_QUERY_STRING = 'UPDATE_QUERY_STRING';
export const UPDATE_QUERY_OBJECT = 'UPDATE_QUERY_OBJECT';
export const UPDATE_FILTER_OBJECT = 'UPDATE_FILTER_OBJECT';
export const CLEAR_WORKSPACE = 'CLEAR_WORKSPACE';

export const PUSH_ITEMS_TO_STORE = 'PUSH_ITEMS_TO_STORE';
export const REPLACE_ITEMS = 'REPLACE_ITEMS';
export const CLEAR_ITEMS = 'CLEAR_ITEMS';
export const UPDATE_ITEM = 'UPDATE_ITEM';

export const SET_VIEWS = 'SET_VIEWS';
export const SELECT_VIEW = 'SELECT_VIEW';
export const UPDATE_VIEW = 'UPDATE_VIEW';

export const UPDATE_COLUMN_VISIBILTY = 'UPDATE_COLUMN_VISIBILTY';
export const SET_ALL_COLUMNS_VISIBLE = 'SET_ALL_COLUMNS_VISIBLE';
export const UNSET_ALL_COLUMNS_VISIBLE = 'UNSET_ALL_COLUMNS_VISIBLE';

export const RUN_FILTER = 'RUN_FILTER';
export const RESET_FILTERS = 'RESET_FILTERS';
