export const __TEST_RUNNER = '__TEST_RUNNER';

export const ADD_ITEM_TO_WORKSPACE = 'ADD_ITEM_TO_WORKSPACE';
export const REMOVE_ITEM_FROM_WORKSPACE = 'REMOVE_ITEM_FROM_WORKSPACE';
export const UPDATE_QUERY_STRING = 'UPDATE_QUERY_STRING';
export const UPDATE_QUERY_OBJECT = 'UPDATE_QUERY_OBJECT';
export const CLEAR_WORKSPACE = 'CLEAR_WORKSPACE';

export const PUSH_ITEMS_TO_STORE = 'PUSH_ITEMS_TO_STORE';
export const REPLACE_ITEMS_IN_STORE = 'REPLACE_ITEMS_IN_STORE';
export const CLEAR_ITEMS_IN_STORE = 'CLEAR_ITEMS_IN_STORE';
export const UPDATE_ITEM_IN_THE_STORE = 'UPDATE_ITEM_IN_THE_STORE';
